### ISSUE TITLE
Faster downloading using fragments and aria2c

### ISSUE THREAD

**Issue by saltrocks** [Owez/yark#109]
https://www.reddit.com/r/youtubedl/comments/rk756f/ytdlp_downloads_at_100kbs/hpffeeu/

**Comment by Owez** [comment]
It's a shame that this happens. Because internally all the videos are passed into yt-dlp at once, setting concurrent fragments shouldn't be too much of an issue. I'm full up with work for the new GUI at the moment (#105) so I'm sorry I couldn't get to this sooner.

I'll see if I can fix now, if not it might have to be after the March release where I have more time.

**Comment by Owez** [comment]
Yep its an easy fix, I've enabled concurrent fragments and pushed as `1.2.5` available now. You can download by doing `pip3 install yark --upgrade`. I can't test right now because my wifi is too slow but this should work

**Comment by Owez** [comment]
Closed by bac4711ddf8ff4da3fe4366ee61a73ba6fc60614
