### ISSUE TITLE
Migrating from master to pypi.org version

### ISSUE THREAD

**Issue by nmcgill** [Owez/yark#115]
I've installed the github master branch version of yark since it had a feature I needed at the time. I have some large channels archived on this version with some videos no longer available.

It seems that the version on pypi.org is more maintained and it makes sense to migrate all of my archives to this version. While on the PyPI version (2.8.1 currently from April 28), if I attempt to `yark refresh` on a archive created from the github master branch, I receive the following:

```
Automatically migrating archive from v4 to v3, a backup has been made at <channel name>.yark.bak
Unknown archive version v4 found during migration
```

I understand this is not an intended use-case of yark, and this message is expected coming from the master branch version which is incompatible. However, is there any manual migration I can run that will fix the metadata in my archives to become compatible with v3?

**Comment by Owez** [comment]
No worries, I’ll write a script later today to migrate your v4 down to v3. The master branch is a bit unstable because I’ve been working on a full rewrite in the background for the last while and I’ve not had time to bug fixSent from my iPhoneOn 16 May 2023, at 21:12, Nevan McGill ***@***.***> wrote:﻿
I've installed the github master branch version of yark since it had a feature I needed at the time. I have some large channels archived on this version with some videos no longer available.
It seems that the version on pypi.org is more maintained and it makes sense to migrate all of my archives to this version. While on the PyPI version (2.8.1 currently from April 28), if I attempt to yark refresh on a archive created from the github master branch, I receive the following:
Automatically migrating archive from v4 to v3, a backup has been made at <channel name>.yark.bak
Unknown archive version v4 found during migration

I understand this is not an intended use-case of yark, and this message is expected coming from the master branch version. However, is there any manual migration I can run that will fix the metadata in my archives to become compatible with v3?

**Comment by Owez** [comment]
﻿No worries, I’ll write a script later today to migrate your v4 down to v3. The master branch is a bit unstable because I’ve been working on a full rewrite in the background for the last while and I’ve not had time to bug fix

**Comment by Owez** [comment]
https://github.com/owez/yarkv4v3 :)

**Comment by nmcgill** [comment]
Works great, thank you!!
