### ISSUE TITLE
Flat directory structure

### ISSUE THREAD

**Issue by lostmsu** [Owez/yark#136]
Please add an option for flat directory structure where all videos and thumbnails go directly into the archive folder.

This would make it easier to interact with the archive using media center apps like Kodi or just browsing it using file explorer.

For the latter to make it seamless it might make sense to:
 - name video files `<title> [<id>].<ext>`
 - set the file creation and/or modification dates to the publication date of the video

**Comment by Owez** [comment]
Hi, I'll see what I can do but it might be a pain given that the frontend templating assumes the paths. It might be worth using the [`yt-dlp`](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#installation) tool directly because I think it does output a ton of flat videos into a folder by default.

Something like:

```shell
$ yt-dlp https://www.youtube.com/@owez7113
```

Should hopefully download them like that for now 🤞
