### ISSUE TITLE
Download Videos in 1080p

### ISSUE THREAD

**Issue by ameyoyo** [Owez/yark#58]
Hi, first I would like to thank you for making this program. 

There's an issue that I want to bring up that although that the command line program will show that the videos downloaded are in 1080p, inspecting the video files themselves will show that they are actually in 720p. 
<img width="516" alt="image" src="https://user-images.githubusercontent.com/47435073/211063066-aac2101d-979a-4294-82ed-afe5dccd3fcb.png">

Is there a way to force it to download a certain quality when archiving...? Thanks.

**Comment by Owez** [comment]
Thanks! The resolution shown there is the best quality resolution youtube knows about. In version 1.2 (the current version) Yark is limited to 720p max downloads. 

In the new v1.3 coming out in a month I'll hopefully be able to fix this so that Yark downloads 1080p by default, with settings to get lower or even higher resolutions. Here's the issue where you can track the progress: #59
